name: Rust
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python and development headers
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python development headers
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        run: cargo build --verbose
        env:
          LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          PYO3_PYTHON: /usr/bin/python3

      - name: Run tests
        run: cargo test --verbose
        env:
          LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          PYO3_PYTHON: /usr/bin/python3

